// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9j52JdtWK_HhvTkpoTOR1XjRWicV92XA',
    appId: '1:59192587555:web:73185d3fbec30b5603c896',
    messagingSenderId: '59192587555',
    projectId: 'chatapp-9a01f',
    authDomain: 'chatapp-9a01f.firebaseapp.com',
    storageBucket: 'chatapp-9a01f.firebasestorage.app',
    measurementId: 'G-4DEBBYSPKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBomeVQBfo1Q7WORN4eWH-KPT0jhtsTUnI',
    appId: '1:59192587555:android:2ba22602aeb8d61103c896',
    messagingSenderId: '59192587555',
    projectId: 'chatapp-9a01f',
    storageBucket: 'chatapp-9a01f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFk6hV16bNIlyzvh9QSEUKd8AaKdkrVBw',
    appId: '1:59192587555:ios:a6badcc10e7e79cc03c896',
    messagingSenderId: '59192587555',
    projectId: 'chatapp-9a01f',
    storageBucket: 'chatapp-9a01f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFk6hV16bNIlyzvh9QSEUKd8AaKdkrVBw',
    appId: '1:59192587555:ios:a6badcc10e7e79cc03c896',
    messagingSenderId: '59192587555',
    projectId: 'chatapp-9a01f',
    storageBucket: 'chatapp-9a01f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9j52JdtWK_HhvTkpoTOR1XjRWicV92XA',
    appId: '1:59192587555:web:5bd477232d69f0ee03c896',
    messagingSenderId: '59192587555',
    projectId: 'chatapp-9a01f',
    authDomain: 'chatapp-9a01f.firebaseapp.com',
    storageBucket: 'chatapp-9a01f.firebasestorage.app',
    measurementId: 'G-3Z42M2TEM8',
  );
}
